### ISSUE TITLE
A test of image display in pinned gists. Not useful, just for fun.

### ISSUE THREAD

**Issue by Gerhut** [matchai/awesome-pinned-gists#2]
Show most used Pokémon in online battles of Pokémon Global Link in pinned gists.

Preview at <https://github.com/Gerhut>

Source code is at <https://github.com/Gerhut/PokemonRanks>

**Comment by johnletey** [comment]
@Gerhut I love how you implemented this in Python. @matchai we could probably list this under a "Fun" section?

**Comment by ChrisCarini** [comment]
Hi @Gerhut - it looks like the preview is no longer showing (understandable, it has been several years since you opened this issue). I quickly looked at the code, and it seems, at the very least, that the URL for the images is no longer working. 

Are you able to get it working once again, or would you prefer this issue is closed out?
